name: Generate ASCII Artwork

on: push

jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Cowsay Program
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Execute cowsay CMD
        run: cowsay -f dragon "RUN for cover, I am DRAGON.....RAWR" >> dragon.txt

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

      - name: List Repo Files
        run: ls -ltra
